name: Semgrep

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "37 3 * * 4"

permissions:
  contents: read

jobs:
  semgrep:
    uses: jotaele44/thehub-pr/.github/workflows/semgrep.yml@8b877ffe6ba031ad474f700a8f88e23a3573582a
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
